#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Install OS-level packages first
if [ "$(uname -s)" = "Darwin" ]; then
  echo "› brew bundle"
  brew bundle
elif [ -f /etc/debian_version ]; then
  echo "› install linux packages"
  ./linux/install-packages.sh
fi

echo "› run all install.sh scripts"
find . -name install.sh ! -path './linux/*' | while read installer ; do sh -c "${installer}" ; done
