#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

echo "› run all install.sh scripts"
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

echo "› brew bundle"
brew bundle
